### ISSUE TITLE
In-game gui for adjusting parts

### ISSUE THREAD

**Issue by LemmaEOF** [Gamepiaynmo/CustomModel#1]
A gui would really help make it easier to edit your model and see what it'll look like in-game. I might be able to help make the gui stuff you'd need for that if you want!

**Comment by Gamepiaynmo** [comment]
That will be nice. I' ll be very appreciated if you can help!

**Comment by HexBugOrion** [comment]
Hecc yeah!

**Comment by Gamepiaynmo** [comment]
An ingame gui for model selection is added to the mod. There is no further plan on an ingame model editing gui.
