### ISSUE TITLE
Inventory character glitched

### ISSUE THREAD

**Issue by ColinTimBarndt** [Gamepiaynmo/CustomModel#10]
When opening the inventory, some rotations are fixed to the in-game player and some on the inventory-player (see screenshot).
![Inventory](https://user-images.githubusercontent.com/26167910/67160449-16af5280-f351-11e9-838d-2fd02b2b6d64.png)

Affects the latest version

How it should look like:
![grafik](https://user-images.githubusercontent.com/26167910/67160471-5ece7500-f351-11e9-9f17-ef154c81b8a1.png)

**Comment by GreenShaman** [comment]
I've got this problem too.
