### ISSUE TITLE
Crash when unloading dimensions, (and maybe) improper config sync, unable to preserve player model after logout.

### ISSUE THREAD

**Issue by dragon-evol** [Gamepiaynmo/CustomModel#13]
- Java Version: 1.8.0_181
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- OptiFine: 1.12.2_HD_U_F6_pre1
- Mod present: Only CPM

Well, first of all this is really an amazing mod, and I really enjoyed it. (And sorry for my bad English)

But the problem is that whenever I return to Overworld from Nether, the game crashes with "No OpenGL context found" when "release ModelPack", and the problem can be easily reproduced (even with models in Example like Steve), and the problem stayed there though I tried to compile a "latest version" from the code on Github. The crash report is in the attached file.

[crash-2020-01-23_12.52.48-server.txt](https://github.com/Gamepiaynmo/CustomModel/files/4101414/crash-2020-01-23_12.52.48-server.txt)

So, I just brutally deleted the release operation when unloading worlds in the code and the problem magically disappeared.

- The version I edited is the version uploaded on yesterday noon.

However I found that after an cross-dimensional trip, the config seemed to be messed up, and my Bounding Box is reset to default (1.8 blocks). So, I deleted the initServerStatus() in onWorldUnload as well. (onWorldUnload now does nothing) That problem magically disappeared as well.

Buuut there comes another problem which is that the player's model is set to default when the player log in, and manually edit the json file (custom-models.json) on both sides before logging in doesn't fix it. (model in both json files become "default" when I log in) I guess there may be something wrong with the network part?

I didn't manage to fix that so here's the issue. Or maybe I messed something up when deleting the contents in onWorldUnload?

Hope this got fixed and the mod becomes better and better!

Besides, the Gui of the newly added but not released feature is just empty, and the command "select" doesn't seem to work on server side, giving an error of "you must specify a player to perform this action on" or something, but the client can type and execute it well, apart from the tab function for selecting models doesn't work. Maybe is feature is under progress and not finished?

**Comment by dragon-evol** [comment]
Update! I deleted the clearModels in onMessage in PacketConfig, and the problem is fixed!

**Comment by Gamepiaynmo** [comment]
Thanks for this detailed issue report. The information provided is really helpful for a mod developer.

It makes me realize that subscribing world unloading is not a good way to release resources when exit. I modified the resource releasing part and the problems are solved.

P.S. The command select requires you to specify a player if you are running this in the server console, like /custommodel select alex Gamepiaynmo.
