### ISSUE TITLE
Lower boxes, quads, & particles do not render behind higher translucent textures

### ISSUE THREAD

**Issue by floral-qua-floral** [Gamepiaynmo/CustomModel#18]
When any translucent texture is included in a custom model, regardless of whether it is part of a skin or an included texture and regardless of whether it's in a box or a quad, it will prevent any model parts created _below_ where it is created from rendering behind it.

I've put together a slightly modified version of the example [Asada Shino](https://github.com/Gamepiaynmo/CustomModel/tree/master/examples/asada_shino) model to demonstrate the issue:
[asada_shino_lens.zip](https://github.com/Gamepiaynmo/CustomModel/files/4143670/asada_shino_lens.zip)
I added a black "lens" at the very top of the bone list, and a purpley-pink "lens" a bit lower down. Both lenses are just translucent quads attached to the Body bone, that float a short distance in front of the player. She has also been made to be permanently blinking, just to make the issue a little easier for me to screenshot.

Because the black "lens" is defined at the top, the entire model is invisible behind it:
![image](https://user-images.githubusercontent.com/49110090/73604847-fa27d680-454b-11ea-983d-67209960c33a.png)

However, because the purpley-pink "lens" is defined below some elements, some parts of the model can be seen behind it:
![image](https://user-images.githubusercontent.com/49110090/73604859-1461b480-454c-11ea-9d7b-3cfcaed8ec8f.png)
The elements that are visible (one arm, her blinking texture) are visible because they are defined _above_ the purpley-pink lens. Any elements defined below, such as her body or her head's boxes, do not display properly.

**Comment by Gamepiaynmo** [comment]
It's a common bug in almost all 3D games. The only way to prevent it from happening is carefully adjust the order these bones get rendered. This should be the duty of the model makers, as they can change the order in the json file.
