### ISSUE TITLE
Model presets

### ISSUE THREAD

**Issue by LemmaEOF** [Gamepiaynmo/CustomModel#2]
I tend to switch around my model based on the situation, and I'd love if that was easier to do. Having a way to store preset JSONs and swap them without having to directly manipulate files would be really nice.

**Comment by Gamepiaynmo** [comment]
That is a nice idea. I think allowing to add multiple models into one zip should work. It is on the schedule.

**Comment by Gamepiaynmo** [comment]
Players can now easily switch their models ingame.
