### ISSUE TITLE
Lack of a rotation offset

### ISSUE THREAD

**Issue by GreenShaman** [Gamepiaynmo/CustomModel#3]
As the title implies, for making parts like wings and using another object, such as the body, as a parent, rotating it causes some weird rotations due to the axis being the center of the parent object with no option to offset the point at which the part can rotate.

**Comment by Gamepiaynmo** [comment]
It is intended. You can add one bone only for offsetting, and another bone as the former's child. This is what i did in the example "Black Rock Shooter".
