### ISSUE TITLE
Invisible held items and worn armour?

### ISSUE THREAD

**Issue by GreenShaman** [Gamepiaynmo/CustomModel#4]
![image](https://user-images.githubusercontent.com/7545132/63893474-27db8300-c9e2-11e9-94fc-d398fcb82a6a.png)
Held items and armour are not visible on the player, intentional?

**Comment by GreenShaman** [comment]
Also, a possible suggestion, picking which bones hold each the left and right hand items would be very nice.

**Comment by Gamepiaynmo** [comment]
It is a bug definitely. Will be fixed next update. Thanks for pointing that out. As for the suggestion, i am looking for an elegant way to achieve that.
