### ISSUE TITLE
[Suggestion] It would be nice if there was an import/converter from something like optifine models or java entity models

### ISSUE THREAD

**Issue by SHsuperCM** [Gamepiaynmo/CustomModel#5]
Because it's really annoying to model things through text files, it would really really be helpful if it imported something like an optifine mob model or a .java entity model since alot of minecraft modeling software can export to these model types..
I am personally modeling using [BlockBench](https://blockbench.net/) so it would be also sweet if instead there was an export plugin to CustomModel models.

**Comment by Gamepiaynmo** [comment]
Yeah that is kind of necessary. I will take a look at BlockBench soon.
