### ISSUE TITLE
Incorrect crouching state and animation syncing

### ISSUE THREAD

**Issue by GreenShaman** [Gamepiaynmo/CustomModel#8]
https://i.imgur.com/lRWT6wS.gifv
https://i.imgur.com/BuEa97v.gifv
The image speak for themselves, it's not taking the crouching state from the correct client, only the viewer.

**Comment by Gamepiaynmo** [comment]
I cannot reproduce it. Are you using the latest version?

**Comment by GreenShaman** [comment]
When the viewing player is in 3rd person, for some reason the crouching syncs up with their model and not the other player's models with themselves.
This happens not to hard position parts but physics parts.
 Attempt this with physics parts.

**Comment by GreenShaman** [comment]
I'm unsure if it's a mod conflict, I should test more.

**Comment by GreenShaman** [comment]
https://i.imgur.com/vODerLa.gifv
https://i.imgur.com/OIu1TDY.gifv
I'm testing this out in LAN.
Mods:
  [✔️] cpm-1.0.3-beta
  [✔️] data-loader-1.1.0+mc1.14.4
  [✔️] DiUI-1.0.4.1
  [✔️] fabric-api-0.3.3+build.234-1.14
  [✔️] fabric-language-kotlin-1.3.40+build.1
  [✔️] GamemodeOverhaul-1.0.1.1
  [✔️] i-am-very-smart-1.5.0+mc1.14.4
  [✔️] level-up-hp-4.4.0+mc1.14.4
  [✔️] malilib-fabric-1.14.4-0.10.0-dev.20
  [✔️] modmenu-1.7.10+build.119
  [✔️] nomoreglowingpots-1.14-1.0.0
  [✔️] torohealth-1.14.4-fabric-3
These are all the mods I'm using to test models.

"I cannot reproduce it. Are you using the latest version?"
Also, yeah, I'm using the latest version.

**Comment by GreenShaman** [comment]
> I cannot reproduce it. Are you using the latest version?

Also, yeah, I'm using the latest version.
