### ISSUE TITLE
Particles in horizontal animations not moving down

### ISSUE THREAD

**Issue by ColinTimBarndt** [Gamepiaynmo/CustomModel#9]
When in the swimming animation/crawling/flying with elytra, particle do not move relative to the player model.
### How to reproduce
Use a model with particles (like the "black_rock_shooter" example model) and go into one of the animations listed above
### Screenshots
_The red bar is from another mod_
![Swimming](https://user-images.githubusercontent.com/26167910/66571511-b3166f80-eb6f-11e9-8dc5-b1eca4f8c7ca.png)
![Crawling](https://user-images.githubusercontent.com/26167910/66571592-da6d3c80-eb6f-11e9-88cb-db1769da2023.png)
![Flying](https://user-images.githubusercontent.com/26167910/66571711-08eb1780-eb70-11e9-840e-41363383704a.png)

**Comment by GreenShaman** [comment]
I've experienced this too, can confirm.

**Comment by Gamepiaynmo** [comment]
Fixed in the latest update.
